### ISSUE TITLE
EADDRINUSE on activated config reload

### ISSUE THREAD

**Issue by gebi** [etsy/statsd#462]
Hi,

When config reload is enabled statsd aborts on any config changes because it reports an exception with EADDRINUSE. Disabling config reload removes the problem.

**statsd version:**
0.7.2~g6bfa42c (debian package built from git version g6bfa42c)

**config:**
{ address: "127.0.0.1",
  mgmt_address: "127.0.0.1",
  graphitePort: 2003,
  graphiteHost: "10.11.2.30",
  graphite: {
    globalPrefix: "stats.prod",
    globalSuffix: require('fs').readFileSync('/etc/clusternodename', encoding='utf8').split('\n')[0].split('.')[0],
    legacyNamespace: false,
  },
  percentThreshold: [5,10,90,95,99],
  deleteIdleStats: true,
  debug: true,
  automaticConfigReload: true,
}

**Exception:**
...
17 Oct 11:06:08 - reading config file: /etc/statsd/localConfig.js
17 Oct 11:06:08 - DEBUG: Loading server: ./servers/udp
17 Oct 11:06:08 - server is up
17 Oct 11:06:08 - DEBUG: Loading backend: ./backends/graphite
17 Oct 11:06:08 - DEBUG: numStats: 4
17 Oct 11:06:08 - DEBUG: numStats: 4

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at net.js:1146:9
    at dns.js:72:18
    at process._tickCallback (node.js:419:13)

ps.: thx for the new fixes for building a debian package :)!

**Comment by janpapenbrock** [comment]
:+1: same problem here

**Comment by BenjaminWinks** [comment]
the "automaticConfigReload: false" didn't work for me, I have the same error.

I cloned the repo, I made a config file from the example, I did "npm install nodeunit" and then "npm install" and then ./run_tests.sh, and I keep getting the same error. Any ideas/help? Thanks.

**Comment by pathzzrd** [comment]
Still not sure where this is at but it's not getting fixed for 0.8.0

**Comment by gebi** [comment]
Thx for statsd, it served us really well through the years!
Though i can not further monitor this bug because we don't use statsd anymore (we _heavily_ outgrew it ;)

**Comment by pathzzrd** [comment]
I'm thinking of dropping this feature entirely, a statsd restart takes a negligible amount of time
