### ISSUE TITLE
statsd doesn't accept config file

### ISSUE THREAD

**Issue by amos-stan** [etsy/statsd#486]
I have the following configuration file, generated using Puppetlabs Operarions' statsd Puppet module (https://github.com/puppetlabs-operations/puppet-statsd):
```
{
  backends: [  "../stackdriver-statsd-backend/lib/stackdriver.js",
  ]
, graphitePort: "2003"
, graphiteHost: "localhost"
, address: "0.0.0.0"
, port: "8125"
, flushInterval: "10000"
, percentThreshold: [90]
, stackdriver: { apiKey: "YOUDIDNTREALLYEXPECTTHEREALKEYHEREDIDYOU" }
}
```
And the error I get when I try to execute statsd is:
```
# /usr/local/sbin/statsd /etc/statsd/localConfig.js /var/log/statsd/statsd.log
Running /usr/bin/nodejs /etc/statsd/localConfig.js /var/log/statsd/statsd.log

/etc/statsd/localConfig.js:4
, graphitePort: "2003"
              ^
SyntaxError: Unexpected token :
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```
System is Ubuntu 14.04 LTS x64, node is v0.10.36 installed from nodesource.com's Ubuntu package (https://github.com/nodesource/distributions). I also tested this with Ubuntu's built-in node package (v0.10.25) and get the same error.

So far I can't tell what's wrong with this configuration.

I also tested the exampleConfig.js file from https://raw.githubusercontent.com/etsy/statsd/master/exampleConfig.js and get the same error.

What am I missing?

Thanks.

**Comment by amos-stan** [comment]
Ignore this - I was running statsd with the wrong paths.
