### ISSUE TITLE
fix travis build

### ISSUE THREAD

**Issue by mrtazz** [etsy/statsd#490]
seems like something is wrong with the `deep-equal` module which makes the build fail on node v0.8.0

```
npm http GET https://registry.npmjs.org/nodeunit
npm http 304 https://registry.npmjs.org/nodeunit
npm ERR! Error: No compatible version found: deep-equal@'^1.0.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.0","0.1.0","0.1.1","0.1.2","0.2.0","0.2.1","0.2.2","1.0.0"]
npm ERR!     at installTargetsError (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /home/travis/.nvm/v0.8.28/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at RegClient.get_ (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:101:14)
npm ERR!     at RegClient.<anonymous> (/home/travis/.nvm/v0.8.28/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:37:12)
npm ERR!     at fs.readFile (fs.js:181:14)
npm ERR!     at Object.oncomplete (fs.js:302:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! System Linux 2.6.32-042stab090.5
npm ERR! command "/home/travis/.nvm/v0.8.28/bin/node" "/home/travis/.nvm/v0.8.28/bin/npm" "install"
npm ERR! cwd /home/travis/build/etsy/statsd
npm ERR! node -v v0.8.28
npm ERR! npm -v 1.2.30
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/travis/build/etsy/statsd/npm-debug.log
npm ERR! not ok code 0
The command "eval npm install " failed 3 times.
The command "npm install " failed and exited with 1 during .
```

**Comment by mrtazz** [comment]
fixed with https://github.com/etsy/statsd/commit/20e353840528104750729bd8008a418a5b595b6a
