### ISSUE TITLE
repeater backend doesn't work with tcp server

### ISSUE THREAD

**Issue by ebroder** [etsy/statsd#508]
The repeater backend requires a Buffer (because dgram.Socket.send does), which it gets from the UDP server (because that's what the dgram.Socket message event returns), but not from the TCP server (because it slices a string and returns that). This means that enabling the repeater backend with a TCP server causes this error:

```
dgram.js:249
    throw new TypeError('First argument must be a buffer object.');
          ^
TypeError: First argument must be a buffer object.
    at Socket.send (dgram.js:249:11)
    at RepeaterBackend.process (statsd/backends/repeater.js:30:15)
    at EventEmitter.<anonymous> (statsd/backends/repeater.js:23:55)
    at EventEmitter.emit (events.js:98:17)
    at statsd/stats.js:195:21
    at Socket.<anonymous> (statsd/servers/tcp.js:21:14)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
```

I'm not sure whether it makes more sense for the repeater backend to cast to a Buffer as necessary, or for the TCP server to be returning Buffers instead of strings. Writing the code for either is fairly easy - I have sketches of both and would be happy to open a PR with some guidance on which is preferable.

**Comment by james-lawrence** [comment]
someone did some of the prelim work as well (different approach as i recall)
https://github.com/etsy/statsd/pull/446

**Comment by mrtazz** [comment]
closed with https://github.com/etsy/statsd/pull/521

Thanks for submitting this issue!
